export function exportHTML(content: string, filename = 'output', metadata: { title?: string } = {}) {
  const html = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${metadata.title || 'Teaching AI Output'}</title>
  <style>
    body {
      font-family: 'Noto Sans KR', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #111827;
      line-height: 1.7;
    }
    h1 { font-size: 28px; color: #1B3A6B; margin-bottom: 24px; }
    h2 { font-size: 22px; color: #1B3A6B; margin: 24px 0 12px; }
    h3 { font-size: 18px; margin: 16px 0 8px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { border: 1px solid #E5E7EB; padding: 10px 14px; text-align: left; }
    th { background: #F5F7FA; font-weight: 600; }
    blockquote { border-left: 4px solid #1B3A6B; padding: 12px 20px; margin: 12px 0; background: #F5F7FA; }
    code { background: #F5F7FA; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
    pre { background: #1E293B; color: #E2E8F0; padding: 16px; border-radius: 8px; overflow-x: auto; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; font-size: 12px; color: #9CA3AF; }
  </style>
</head>
<body>
  ${markdownToHtml(content)}
  <div class="footer">Generated by Teaching AI | ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function markdownToHtml(md: string): string {
  let html = md
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')
    .replace(/^\- (.*$)/gm, '<li>$1</li>')
    .replace(/^\d+\. (.*$)/gm, '<li>$1</li>');

  // Handle tables
  const lines = html.split('\n');
  let result = [];
  let inTable = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      if (/^\|[\s-:|]+\|$/.test(trimmed)) continue;
      const cells = trimmed.split('|').filter(Boolean).map(c => c.trim());
      if (!inTable) {
        result.push('<table>');
        result.push('<tr>' + cells.map(c => `<th>${c}</th>`).join('') + '</tr>');
        inTable = true;
      } else {
        result.push('<tr>' + cells.map(c => `<td>${c}</td>`).join('') + '</tr>');
      }
    } else {
      if (inTable) {
        result.push('</table>');
        inTable = false;
      }
      result.push(trimmed ? `<p>${trimmed}</p>` : '');
    }
  }
  if (inTable) result.push('</table>');

  return result.join('\n');
}
