import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * HTML DOM 캡처 기반 PDF 내보내기 (한글 완벽 지원)
 * outputEl이 제공되면 DOM 캡처, 없으면 텍스트 폴백
 */
export async function exportPDF(content: string, filename = 'output', metadata: Record<string, unknown> = {}, outputEl: HTMLElement | null = null) {
  if (outputEl) {
    return exportPDFFromDOM(outputEl, filename);
  }
  return exportPDFText(content, filename, metadata);
}

async function exportPDFFromDOM(el: HTMLElement, filename: string) {
  // 캡처를 위한 임시 클론 (화면 스크롤 영향 제거)
  const clone = el.cloneNode(true) as HTMLElement;
  clone.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 800px; padding: 40px;
    background: #fff; color: #1a1a1a;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    overflow: visible; max-height: none; height: auto;
  `;
  document.body.appendChild(clone);

  try {
    const canvas = await html2canvas(clone as HTMLElement, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      windowWidth: 800,
    });

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const imgWidth = 170; // A4 content width in mm (210 - 40 margin)
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageHeight = 277; // A4 content height (297 - 20 margin)
    let position = 10;
    let remainingHeight = imgHeight;
    let pageNum = 1;

    // 헤더
    addHeader(doc);

    position = 20;

    if (remainingHeight <= pageHeight - position) {
      // 한 페이지에 들어가는 경우
      doc.addImage(imgData, 'JPEG', 20, position, imgWidth, imgHeight);
    } else {
      // 여러 페이지에 걸쳐 출력
      let srcY = 0;
      while (remainingHeight > 0) {
        if (pageNum > 1) {
          doc.addPage();
          addHeader(doc);
          position = 20;
        }

        const availableHeight = pageHeight - position;
        const sliceHeight = Math.min(remainingHeight, availableHeight);
        const sliceRatio = sliceHeight / imgHeight;

        // 캔버스에서 해당 부분만 잘라서 삽입
        const sliceCanvas = document.createElement('canvas');
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = Math.ceil(canvas.height * sliceRatio);
        const ctx = sliceCanvas.getContext('2d');
        ctx?.drawImage(
          canvas,
          0, srcY, canvas.width, sliceCanvas.height,
          0, 0, sliceCanvas.width, sliceCanvas.height
        );

        const sliceImg = sliceCanvas.toDataURL('image/jpeg', 0.95);
        doc.addImage(sliceImg, 'JPEG', 20, position, imgWidth, sliceHeight);

        srcY += sliceCanvas.height;
        remainingHeight -= sliceHeight;
        pageNum++;
      }
    }

    // 푸터
    addFooter(doc);

    doc.save(`${filename}.pdf`);
  } finally {
    document.body.removeChild(clone);
  }
}

function addHeader(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Teaching AI', 20, 8);
  doc.setDrawColor(220);
  doc.line(20, 10, 190, 10);
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Teaching AI | Page ${i}/${pages}`, 20, 290);
  }
}

/**
 * 텍스트 폴백 (DOM 없을 때)
 */
function exportPDFText(content: string, filename: string, _metadata: Record<string, unknown>) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  addHeader(doc);

  doc.setFontSize(11);
  doc.setTextColor(30);

  const lines = doc.splitTextToSize(stripMarkdown(content), 170);
  let y = 20;
  const pageHeight = 280;

  for (const line of lines) {
    if (y > pageHeight) {
      doc.addPage();
      addHeader(doc);
      y = 20;
    }
    doc.text(line, 20, y);
    y += 6;
  }

  addFooter(doc);
  doc.save(`${filename}.pdf`);
}

function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    .replace(/\|/g, ' | ')
    .replace(/-{3,}/g, '');
}
